/* 
Author: Nana Adwoa Ayiw Elegba
Date: 26/04/2025
Description: This code handles the background work like calling the API and sending the result from the API to the frontend (content.js)
*/

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  

  if (message.action === "summarizePage") {
    const pageText = message.text;
    const pageUrl = message.url; // *** Receive the URL from the message ***
    fetch("https://refinesummary-production.up.railway.app/refined", {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      
      body: JSON.stringify({ url: pageUrl }) // *** The API takes a link and so the page link is passed to it***
      
    })
    .then(response => {
        console.log("Background: Fetch response received. Status:", response.status, response);
        if (!response.ok) {
            const errorResponseClone = response.clone();
            errorResponseClone.text().then(text => {
                console.error("Background: HTTP error response body:", text);
            }).catch(e => {
                console.error("Background: Could not read response body for error details:", e);
            });
            throw new Error(`HTTP error! status: ${response.status}`);
        }
        return response.json();
    })
    .then(data => {
      const summaries = data ? data["refined summary"] : null;

      if (summaries && typeof summaries === 'object' && Object.keys(summaries).length > 0) {
        console.log("Background: Summaries are valid. Proceeding to send...");

        console.log("--- Calling generateColorMap with ---", summaries);
        const colors = generateColorMap(summaries);

        console.log("Background: Sending showSummaries message to tab:", sender.tab.id);
        chrome.tabs.sendMessage(sender.tab.id, {
          action: "showSummaries",
          summaries: summaries,
          colors: colors
        }).catch(error => {
             console.error("Background: Error sending showSummaries message back to tab:", error);
        });

      } else {
        console.error("Background: API response did not contain valid 'refined summary' data or was empty:", data);
        chrome.tabs.sendMessage(sender.tab.id, {
            action: "showError",
            message: "Could not get summary data from the service. Response structure invalid."
        }).catch(error => {
             console.error("Background: Error sending invalid data error message back to tab:", error);
        });
      }
    })
    .catch(error => {
      console.error("Background: API Fetch or Processing Error:", error);
       chrome.tabs.sendMessage(sender.tab.id, {
            action: "showError",
            message: `Error communicating with summary service: ${error.message || "Unknown error"}`
       }).catch(error => {
            console.error("Background: Error sending fetch error message back to tab:", error);
       });
    });

    return true;
  }
});

// generateColorMap function is used to assign colours to the summaries generated by successful API response
function generateColorMap(summaries) {
  console.log("--- Inside generateColorMap. Summaries argument:", summaries);
  const colors = ["#C3E9F2", "#DCEEFF", "#C1DAD6", "#D8CFC4", "#DFF2E1"];
  let colorMap = {};
  if (summaries && typeof summaries === 'object') {
      console.log("generateColorMap: summaries is valid object, processing keys.");
      Object.keys(summaries).forEach((heading, index) => {
          colorMap[heading] = colors[index % colors.length];
      });
  } else {
      console.warn("generateColorMap called with invalid summaries data:", summaries);
  }
  return colorMap;
}